### ISSUE TITLE
I just want onpress but not onLongPress

### ISSUE THREAD

**Issue by ngondat97** [mpiannucci/react-native-context-menu-view#12] opened 2020-07-29 10:04 UTC
I just want to click, not the Haptic touch event to show the context menu.
If onLongPress, then show context menu. onPress is the press event like the Touchable events

**Comment by mpiannucci** [comment] 2020-07-29 16:11
Its not currently possible on iOS as far as I can tell, the ContextMenu control is native to `UIView` and the action cannot be customized. It will only work with the longPressed haptic press unfortunately. Sorry

**Comment by jineshshah36** [comment] 2020-09-12 23:04
It looks like iOS 14 supports on press or at least I’m seeing that behavior here (https://developer.apple.com/design/human-interface-guidelines/ios/controls/pull-down-menus/)

**Comment by benandrew** [comment] 2020-10-22 04:09
@mpiannucci Any update on adding onPress support with iOS 14? Similar to @jineshshah36's comment

Thanks

**Comment by mpiannucci** [comment] 2020-10-23 14:50
Ill try to look into it next week

**Comment by zachgibson** [comment] 2020-12-03 00:29
@jineshshah36 that's a pull down menu, not a context menu.

**Comment by mpiannucci** [comment] 2020-12-11 02:43
So according to [this article](https://medium.com/better-programming/whats-new-in-ios-14s-uimenu-and-contextmenu-433cd2037c37) this is done in iOS 14 through setting the `menu` property on `UIButton`.

Knowing this, I think this can be implemented by either subclassjng RCTButton or creating a custom UIButton wrapper (which I don't want to do). I will try to either subclass RCTButton or see what needs to happen to make it work and report back more when I get a chance.

**Comment by mpiannucci** [comment] 2020-12-11 02:51
So it turns out UIButton isn't wrapped by react native core. So to get this functionality, we just have to make a small wrapper around UIBUtton, adding the context menu as to the `menu` property in a similar way to the normal context menus

**Comment by b-derksen** [comment] 2021-04-15 15:00
Any updates on this?

**Comment by avencat** [comment] 2021-05-24 20:50
Hi, I'd like to know if any of you managed to open it with juste an onPress event please? 🙂 @mpiannucci have you any ETA on when this will be possible? 😄

**Comment by zachgibson** [comment] 2021-05-25 17:27
I ended up using https://github.com/dominicstop/react-native-ios-context-menu which supports this.

**Comment by mpiannucci** [comment] 2021-05-25 17:29
@zachgibson thanks for posting. That lib looks really good, and I have very little time to add new features to this one with my job and personal life at the moment.

**Comment by ZerakPalani** [comment] 2022-04-16 14:56
I wanted to use the dominicstop but after a while I realized the button disappears from view when you use navigation.push to another screen and then go back. It becomes a blank space instead of context menu button. So I came here to look at similar solution and this one is good but I need on press, not on long press.

Still good looking, just not going to use it, sadly :(

**Comment by mpiannucci** [comment] 2022-04-18 01:09
Okay So this is supported now for buttons 

https://stackoverflow.com/questions/57744812/how-to-trigger-uicontextmenuinteraction-context-menu-programmatically

But that's doesn't really solve for the more scalable use case, need to look further to find a generic approach

**Comment by mpiannucci** [comment] 2022-04-18 01:15
This might be the ticket https://stackoverflow.com/a/70785208

**Comment by riledv** [comment] 2022-04-18 11:53
@mpiannucci, your library is quite simple and this is its advantage.

It would be cool if this library has the ability to call the menu without a long press and blur.
This is a very important control in recent versions of ios, Apple itself is increasingly using it.

**Comment by mpiannucci** [comment] 2022-04-18 19:21
Alrighty.... this has been merged and published as version `1.5.0` with the new `dropdownMenuMode` prop. 

Let me know if its not working for anyone. Please note, the API is different and it wont show the preview on one press because of the way the iOS APIs restrict the functionality. It also *requires* iOS 14 or else the prop will do nothing.

**Comment by riledv** [comment] 2022-04-20 16:03
@mpiannucci, thank you for doing so quickly.

But it does not working for me.
I am using iOs 14.5 and dropdownMenuMode prop does not working

**Comment by mpiannucci** [comment] 2022-04-20 16:26
Yeah confirmed... idk what went wrong, looking into it

**Comment by mpiannucci** [comment] 2022-04-20 17:19
OKay sorry about that... fixed in 1.5.1

**Closed** 2022-04-20 17:19 UTC

**Comment by riledv** [comment] 2022-04-20 18:52
@mpiannucci, its working completely perfectly, thank you so much
